name: exhibition-3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - cudatoolkit=12.1
  - ffmpeg
  - opencv
  - scikit-image
  - scipy
  - numpy
  - matplotlib
  - tqdm
  - plyfile
  - pandas
  - pip:
    - pyscenespect
    - imagehash
    - imageio
    - imageio-ffmpeg
    - open3d
    - nerfstudio
    - gsplat
    - supervisely
    - pycolmap
    - pillow
    - rich
